config/routes.rb
PpPricing::Application.routes.draw do

  root :to => "products#index"

  resource :sessions, :only=> [:new, :create] do
    collection do
      get 'logout'
    end
  end

  resources :rate_results
  resources :rate_determinants
  resources :price_plans, :constraints => { :id => /.*/ }
  resources :services, :only => [:index, :edit]
  resources :zonal_coverages
  resources :tariff_tier_tapers, :constraints => { :id => /.*/ }
  resources :tariff_zones, :constraints => { :id => /.*/ }
  resources :general_code_items, :only => [:show]
  resources :pricing_structures, :only => [:edit]
  resources :service_characteristics, :only => [:index, :edit]
  resources :promotions, :only => [:index, :edit]
  resources :event_creation_templates, :only => [:index, :edit], :constraints => { :id => /.*/ }

  resources :templates do
    get :select_rate_determinants
    get :select_rate_results
    post :update_with_rates
    post :approve
    resources :rates
  end

  resources :tariff_model_areas, :constraints => { :id => /.*/ } do
    get :approve
    get :revert
    collection do
      post :calculation_options
      post :tmes
    end
  end

  resources :products, :only => [:index, :edit] do
    collection do
      get :synchronize
    end
  end

  resources :rate_tables, :except=> [:update] do
    post :update # changing the default `put update` to a post for use with x-editable
    resources :rate_rows, :only => [:index]
    post :show
  end

  resource :tools, :only=> [:index] do
     collection do
       get 'upload'
     end 
  end 

end

app/views/templates/_attribs.html.erb
<div class="well">
    <% if @template.errors.any? %>
      <ul class="text-error">
        <% @template.errors.each do |error, message| %>
          <li><%= Template.human_attribute_name(error) %> - <%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <table class="table table-condensed no-bottom-margin borderless">
     <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Date</th>
      <th>Status</th>
     </tr>
     <tr>
      <td>
		  <a id='template_code' data-role='editable' data-type='text' data-placement='right'>
		    <%= @template.template_code %>
        </a>
		</td>
      <td>
		  <a id='template_name' data-role='editable' data-type='text' data-placement='right'>
		    <%= @template.template_name %>
		  </a>
		</td>
      <td>
		  <a id='effective_date' data-role='editable' data-type='date' data-format="mm-dd-yyyy" data-placement='right'>
		  <%= @effective_date%>
		  </a>
		</td>
      <td id='effective_status'><%= @template.effective_status %></td>
     </tr>
    </table>
</div>

app/views/templates/_rates.html.erb
<script type="text/javascript">
var jsDeterminants = [<%= raw @determinants.to_json %>];
var jsResults = [<%= raw @results.to_json %>];
</script>
<div id="rate_prompt">ABCD</div>
<div style="float:left">
<div id="determinants-container" class="well rate-container">
   <table>
     <tr>
       <td>
         <button id="add-rate-determinant" class="btn btn-success add-rate-btn"
           data-role="tooltip" title="Add rate determinants"
           data-source="available-determinants" data-target="determinants-table"
           data-class="rate-det-cell" data-offset="0">
           Add Rate Determinant
         </button>
        </td>
     </tr>
     <tr>
  		 <td><%= select_tag("available-determinants",options_from_collection_for_select(@determinants, 'rate_id', 'title'),{:size=>"6", :class=>"rate-box span3"}) %> </td>
     </tr>
   </table>
   <ul class="sortable span3 rate-template-table" id="determinants-table">
          <% @template.template_definitions.each do |column| %>
            <% if column.rate.rate_type == "determinant" %>
               <li tabindex="<%=autotab%>" data-rateid="<%= column.rate_id %>" class="rate-cell rate-det-cell" data-rate="<%=column.as_json%>">
                 <i class="hover ui-icon ui-icon-arrowthick-2-n-s" style="display:inline-block" data-role="move-rate" title="Move rate"></i>
                 <span><%= column.rate.title %></span>
                 <i class="icon-trash hover right-justify" data-role="remove-rate" title="Remove from list"></i>
               </li>
            <% end %>
          <% end %>
    </ul>
</div>
<div id="results-container" class="well rate-container">
<table>
     <tr>
       <td> <button id="add-rate-result" class="btn btn-success add-rate-btn"
         data-role="tooltip" title="Add Rate Result"
         data-source="available-results" data-target="results-table"
         data-class="rate-res-cell" data-offset="10000">
         Add Rate Result </button> </td>
     </tr>
     <tr>
  		 <td><%= select_tag("available-results",options_from_collection_for_select(@results, 'rate_id', 'title'),{:size=>"6", :class=>"rate-box span3"}) %> </td>
     </tr>
   </table>
   <ul class="sortable span3 rate-template-table" id="results-table">
          <% @template.template_definitions.each do |column| %>
            <% if column.rate.rate_type == "result" %>
               <li tabindex="<%=autotab_with_offset(1000)%>" data-rateid="<%= column.rate_id %>" class="rate-cell rate-res-cell"
                  data-role="tooltip" title="bolek">
                 <i class="hover ui-icon ui-icon-arrowthick-2-n-s" style="display:inline-block" data-role="move-rate" title="Move rate"></i>
                 <span><%= column.rate.title %></span>
                 <i class="icon-trash hover right-justify" data-role="remove-rate" title="Remove from list"></i>
               </li>
            <% end %>
          <% end %>
    </ul>
    <ul id="rate-billing-list" class="span3">
      <li id="rate-billing-cell" class="rate-cell">BillingName</li>
    </ul>
</div>
</div>

app/views/templates/_show.html.erb
<div id='usage-template-container'
   data-url="<%= template_update_with_rates_path(@template.template_id) %>" 
	data-loadurl="<%= template_path(@template.template_id) %>"
	data-approveurl="<%= template_approve_path(@template.template_id) %>">
  <%= render "attribs" %>
  <%= render "toolbar" %>
  <%= render "rates" %>
</div>

app/views/templates/_toolbar.html.erb
<div id='pptoolbar' class="container toolbar affix-top" data-spy="affix" data-offset-top="325">
  <div class="btn-toolbar touching_toolbars span8 no-left-margin">
    <div class="btn-group">
      <button class="btn" id="cancel-rates" datarole="tooltip" title="Select Cancel to Cancel all changes">
        <i class="icon-undo"></i> Cancel
      </button>
      <button id="save-rates" class="btn btn-success" data-role="tooltip" title=
        "Select Save to Save all changes">
        <i class="icon-hdd"></i> Save</button>
      <% if session[:user].super_user %>
      <button id="approve-rates" class="btn" data-role="tooltip" title=
        "Select Approve to Approve all changes">
        <i class="icon-hdd"></i> Approve</button>
      <% end %>
    </div>
  </div>
  <div class="btn-toolbar span">
    <div id="rates-loading" class="loading hide"></div>
  </div>
</div>

app/views/templates/_toolbar_new.html.erb
<div id='pptoolbar' class="container toolbar affix-top" data-spy="affix" data-offset-top="325">
  <div class="btn-toolbar touching_toolbars span8 no-left-margin">
    <div class="btn-group">
      <button class="btn" id="template-back" datarole="tooltip" title="Select Cancel to Cancel all changes">
        <i class="icon-undo"></i> Back
      </button>
      <button id="template-create" class="btn btn-success" data-role="tooltip" title=
        "Select Save to Save all changes">
        <i class="icon-hdd"></i> Create</button>
    </div>
  </div>
  <div class="btn-toolbar span">
    <div id="rates-loading" class="loading hide"></div>
  </div>
</div>

app/views/templates/index.html.erb
<% content_for(:page_title) do "Templates" end %>

<h2>Search Rate Table Templates</h2>

<div class="well">

  <form class="span5 form-horizontal search" method="get">
    <input type="text"
      class="input-large"
      placeholder="Usage Template Code"
      name="template_code"
      value="<%=session[:usage_template_code]%>" >
    <input type="text"
      class="input-large"
      placeholder="Usage Template Name"
      name="template_name"
      value="<%=session[:usage_template_name]%>" >
    <div class="btn-group">
      <button class="btn" type="button" data-role="clear-form"><i class="icon-remove"></i></button>
      <button type="submit" class="btn"><i class="icon-search"></i></button>
    </div>
  </form>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th/>
        <th><%=sortable @templates, "Code", "template_code" %></th>
        <th><%=sortable @templates, "Name", "template_name" %></th>
        <th><%=sortable @templates, "Effective Date", "effective_date" %></th>
        <th><%=sortable @templates, "Status", "effective_status" %></th>
      </tr>
    </thead>
    <tbody>
      <% @templates.each do |template| %>
        <tr>
	  <td>
            <%= link_to template_path(template.template_id),
              method: :delete, data: { confirm: "Are you sure you want to completely remove this template with its definition?" } do %>
              <i class="icon-trash hover"> </i>
            <% end %>
	  </td>
          <td><%= link_to template.template_code, template_path(:id=>template.template_id) %></td>
          <td><%= link_to template.template_name, template_path(:id=>template.template_id) %></td>
          <td><%= template.effective_date %></td>
          <td><%= template.effective_status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="container">
    <div class="table-footer span3">
      <%= form_tag({:controller=>:templates, :action=>:index}, :method=>:get) do %>
        <%= select_tag( "amount",
                        options_from_collection_for_select(pagination_options, :last, :first, session[:template_amount]),
                        :class => "input-mini",
                        data: {role: "pagination-amount"} )%>
      <% end %>
    </div>
    <%= paginate @templates %>
  </div>
</div>

app/views/templates/new.html.erb
<% content_for(:page_title) do "Create Template" end %>

<div id="rate-show">
 <h2>Create Rate Table Template</h2>
  <div id='usage-template-container' data-url="<%= templates_path %>"
    data-loadurl="<%= templates_path %>">
    <%= render "attribs" %>
    <%= render "toolbar_new" %>
    <%= render "rates" %>
  </div>
</div>

app/views/templates/show.html.erb
<% content_for(:page_title) do @template.template_code + " | Template" end %>

<div id="rate-show">
 <h2>Edit Rate Table Template</h2>
  <%= render "show" %>
</div>