config/routes.rb
PpPricing::Application.routes.draw do

  root :to => "products#index"

  resource :sessions, :only=> [:new, :create] do
    collection do
      get 'logout'
    end
  end

  resources :rate_results
  resources :rate_determinants
  resources :price_plans, :constraints => { :id => /.*/ }
  resources :services, :only => [:index, :edit]
  resources :zonal_coverages
  resources :tariff_tier_tapers, :constraints => { :id => /.*/ }
  resources :tariff_zones, :constraints => { :id => /.*/ }
  resources :general_code_items, :only => [:show]
  resources :pricing_structures, :only => [:edit]
  resources :service_characteristics, :only => [:index, :edit]
  resources :promotions, :only => [:index, :edit]
  resources :event_creation_templates, :only => [:index, :edit], :constraints => { :id => /.*/ }

  resources :templates do
    get :select_rate_determinants
    get :select_rate_results
    post :update_with_rates
    post :approve
    resources :rates
  end

  resources :tariff_model_areas, :constraints => { :id => /.*/ } do
    get :approve
    get :revert
    collection do
      post :calculation_options
      post :tmes
    end
  end

  resources :products, :only => [:index, :edit] do
    collection do
      get :synchronize
    end
  end

  resources :rate_tables, :except=> [:update] do
    post :update # changing the default `put update` to a post for use with x-editable
    resources :rate_rows, :only => [:index]
    post :show
  end

  resource :tools, :only=> [:index] do
     collection do
       get 'upload'
     end 
  end 

end

app/models/event_creation_template.rb
class EventCreationTemplate < ActiveRecord::Base
  self.table_name = "event_creation_template"
  self.primary_key = "event_creation_template_ver_id"
  
  self.set_boolean_columns "apply_min_period_indicator"
  self.set_boolean_columns "test_mode_ind"
  
  self.set_string_columns "period_type_value"
  
  def charge_occurrence_name
    if self.charge_occurrence_type == "RC"
      "Recurring"
    elsif "OT"
      "One-Time"
    else
      self.charge_occurrence_type
    end
  end
  
  def self.search(filters = {})
    filters.each { |key, value| filters[key] = wildcard(value) if value.class == String}
    
    query = select(
      "ect.event_creation_template_ver_id, ect.code, ect.name, ect.effective_status, ect.effective_date,
       ect.charge_occurrence_type, ect.descriptive_text, s.name as service_name, s.service_code, gci.short_description as usage_mode_name"
    ).from(
      "event_creation_template ect"
    ).joins(
      "left outer join pricing_structure_ect psect
        on ect.event_creation_template_id = psect.event_creation_template_id
      left outer join pricing_structure_price_plan pspp
        on psect.pricing_structure_code = pspp.pricing_structure_code
        and psect.product_version_code = pspp.product_version_code
        and psect.product_code = pspp.product_code
      left outer join price_plan pp
        on pspp.price_plan_code = pp.price_plan_code
      left outer join price_plan_service pps
        on pp.price_plan_version_id = pps.price_plan_version_id
        and upper(pps.service_code) like #{sanitize(filters[:service_code])}
      left outer join service s
        on pps.service_code = s.service_code
        and upper(s.name) like #{sanitize(filters[:service_name])}
      left outer join general_code_item gci
        on gci.group_code = 'USAGE_MODE'
        and ect.usage_mode_value = gci.value"
    ).where(
      "upper(ect.code) like :ect_code
      and upper(ect.name) like :ect_name
      and ect.effective_status like :effective_status
      and ect.usage_mode_value like :usage_mode_value
      and ect.test_mode_ind like :test_mode_ind
      and NVL(ect.change_group_id, ' ') like :change_group_id
      and ect.charge_occurrence_type like :charge_occurrence_type", filters
    ).group(
      "ect.event_creation_template_ver_id, ect.code, ect.name, ect.effective_status, ect.effective_date,
       ect.charge_occurrence_type, ect.descriptive_text, s.name, s.service_code, gci.short_description"
    )
    
    query = query.most_effective if !filters[:search_all_versions]
    return query
  end
  
  def self.for_pricing_structure(pricing_structure_code, product_code, product_version_code)
    select("event_creation_template.*, gci.short_description as usage_mode_name")
    .joins(
      "join pricing_structure_ect psect
        on event_creation_template.event_creation_template_id = psect.event_creation_template_id
      left outer join general_code_item gci
        on gci.group_code = 'USAGE_MODE'
        and event_creation_template.usage_mode_value = gci.value"
    ).where(
      "psect.pricing_structure_code = :pricing_structure_code
      and psect.product_code = :product_code
      and psect.product_version_code = :product_version_code",{
        pricing_structure_code: pricing_structure_code,
        product_code: product_code,
        product_version_code: product_version_code
      }
    )
  end
  
  protected
    
    def self.wildcard(term)
      "%#{term}%".gsub(/\*+/,'%').gsub(/%+/,'%').upcase
    end
    
    def self.most_effective
      where(
        "ect.effective_date =
        (select max(effective_date)
          from event_creation_template ect2
            where ect.event_creation_template_id = ect2.event_creation_template_id
            and effective_date <= :now)",{
        now: DateTime.now
      })
    end
end

app/controllers/event_creation_templates_controller.rb
class EventCreationTemplatesController < ApplicationController
  def index
    setup_sessions
    
    @ects = EventCreationTemplate.search(
      session[:ect_filters].clone
    ).order(
      session[:ect_filters][:order]
    ).page(
      params[:page]
    ).per(
      session[:ect_filters][:amount]
    )
  end
  
  protected
    def setup_sessions
      session[:ect_filters] = params[:ect_filters] || session[:ect_filters] || {
        ect_code: '',
        ect_name: '',
        effective_status: '',
        usage_mode_value: '',
        test_mode_ind: '',
        change_group_id: '',
        charge_occurrence_type: '',
        amount: '10',
        search_all_versions: false
      }
      
      session[:ect_filters][:order] = params[:order] || session[:ect_filters][:order] || 'ect.code asc'
    end
end

app/views/event_creation_templates/index.html.erb
<% content_for(:page_title) do "ECTs" end %>

<h2>Search Event Creation Templates</h2>

<div class="well well-small">
  <form class="search form-inline" method="get">
    <div class="controls controls-row">
      <div class="span no-left-margin">
        <%= text_field_tag("ect_filters[ect_code]", session[:ect_filters][:ect_code],{:placeholder=>"ECT Code"})%>
        <%= text_field_tag("ect_filters[ect_name]", session[:ect_filters][:ect_name],{:placeholder=>"ECT Name"})%>
        <%= select_tag 'ect_filters[effective_status]',
              options_for_select([["Active","ACTIVE"],["Approved","APPRVD"],["Draft","DRAFT"]], session[:ect_filters][:effective_status]),
              :class => 'input-large',
              :prompt => 'Status',
              :data => {:role => "select2"} %>
        
        <label>
          <%= check_box_tag 'ect_filters[search_all_versions]', true, session[:ect_filters][:search_all_versions] %>
          Include all Versions
        </label>
      </div>
    </div>
    
    <div class="controls controls-row">
      <div class="span no-left-margin">
        <%= select_tag 'ect_filters[usage_mode_value]',
              options_from_collection_for_select( GeneralCodeItem.where(group_code: 'USAGE_MODE'), :value, :short_description, :selected=>session[:ect_filters][:usage_mode_value]) ,
              :prompt => 'Usage Mode',
              :data => {:role => "select2"} %>
        <%= select_tag "ect_filters[test_mode_ind]", options_for_select([["Yes","Y"],["No","N"]], session[:ect_filters][:test_mode_ind]), { :prompt=>'Test Mode', :data=>{:role=>'select2'}} %>
        <%= text_field_tag("ect_filters[change_group_id]", session[:ect_filters][:change_group_id],{:placeholder=>"Change Group ID"})%>
      </div>
    </div>
    
    <div class="controls controls-row">
      <div class="span no-left-margin">
        <%= text_field_tag("ect_filters[associated_service_code]", session[:ect_filters][:associated_service_code],{:placeholder=>"Associated Service Code"})%>
        <%= text_field_tag("ect_filters[associated_service_name]", session[:ect_filters][:associated_service_name],{:placeholder=>"Associated Service Name"})%>
        <%= select_tag "ect_filters[charge_occurrence_type]", options_for_select([["One Time","OT"],["Recurring","RC"]], session[:ect_filters][:charge_occurrence_type]), { :prompt=>'Charge Occurrence', :data=>{:role=>'select2'}} %>
      </div>
    </div>
    
    <div class="btn-group">
      <button class="btn" type="button" data-role="clear-form"><i class="icon-remove"></i></button>
      <button type="submit" class="btn"><i class="icon-search"></i></button>
    </div>
  </form>
</div>


<div class="well">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th><%=sortable @ects, "Code", "ect.code" %></th>
        <th><%=sortable @ects, "Name", "ect.name" %></th>
        <th><%=sortable @ects, "Status", "ect.effective_status" %></th>
        <th><%=sortable @ects, "Effective Date", "ect.effective_date" %></th>
        <th><%=sortable @ects, "Service Name", "s.name" %></th>
        <th><%=sortable @ects, "Usage Mode", "gci.short_description" %></th>
        <th><%=sortable @ects, "Charge Occurrence", "ect.charge_occurrence_type" %></th>
        <th><%=sortable @etcs, "Description", "ect.descriptive_text" %></th>
      </tr>
    </thead>
    <tbody>
      <% @ects.each do |ect| %>
        <tr>
          <td><%= link_to ect.code, edit_event_creation_template_path(ect) %></td>
          <td><%= link_to ect.name, edit_event_creation_template_path(ect) %></td>
          <td><%= ect.effective_status %></td>
          <td><%= nullable_date ect.effective_date.to_date %></td>
          <td><%= ect.service_name %></td>
          <td><%= ect.usage_mode_name %></td>
          <td><%= ect.charge_occurrence_name %></td>
          <td>
            <% if ect.descriptive_text && !ect.descriptive_text.empty? %>
              <i class="hover icon-list-alt" data-role="show-popover" data-placement="top"
              data-content="<%= ect.descriptive_text %>" data-original-title="<%= ect.name %>" tabindex="0"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="container">
    <div class="table-footer span3">
      <%= form_tag({:controller=>:products, :action=>:index}, :method=>:get) do %>
        <%= select_tag( "product_filters[amount]",
                        options_from_collection_for_select(pagination_options, :last, :first, session[:product_filters][:amount]),
                        :class => "input-mini",
                        data: {role: "pagination-amount"} )%>
      <% end %>
    </div>
    <%= paginate @ects %>
  </div>
</div>