config/routes.rb
PpPricing::Application.routes.draw do

  root :to => "products#index"

  resource :sessions, :only=> [:new, :create] do
    collection do
      get 'logout'
    end
  end

  resources :rate_results
  resources :rate_determinants
  resources :price_plans, :constraints => { :id => /.*/ }
  resources :services, :only => [:index, :edit]
  resources :zonal_coverages
  resources :tariff_tier_tapers, :constraints => { :id => /.*/ }
  resources :tariff_zones, :constraints => { :id => /.*/ }
  resources :general_code_items, :only => [:show]
  resources :pricing_structures, :only => [:edit]
  resources :service_characteristics, :only => [:index, :edit]
  resources :promotions, :only => [:index, :edit]
  resources :event_creation_templates, :only => [:index, :edit], :constraints => { :id => /.*/ }

  resources :templates do
    get :select_rate_determinants
    get :select_rate_results
    post :update_with_rates
    post :approve
    resources :rates
  end

  resources :tariff_model_areas, :constraints => { :id => /.*/ } do
    get :approve
    get :revert
    collection do
      post :calculation_options
      post :tmes
    end
  end

  resources :products, :only => [:index, :edit] do
    collection do
      get :synchronize
    end
  end

  resources :rate_tables, :except=> [:update] do
    post :update # changing the default `put update` to a post for use with x-editable
    resources :rate_rows, :only => [:index]
    post :show
  end

  resource :tools, :only=> [:index] do
     collection do
       get 'upload'
     end 
  end 

end

app/controllers/rate_tables_controller.rb
class RateTablesController < ApplicationController
  
  def index
    setup_sessions
    @tables = RateTable.search(session[:rate_table_name],
                 session[:rate_table_status],
                 session[:usage_template_name],
                 session[:usage_template_code])
              .order(session[:rate_table_order])
              .page(params[:page])
              .per(session[:rate_table_amount])
  end
  
  def show
    @table = RateTable.get(params[:id] || params[:rate_table_id])
    @new_rows = RateRow.where(:rate_row_id => params[:rate_rows])
  end
  
  def new
    @table = RateTable.new
  end
  
  def update
    table = RateTable.get(params[:rate_table_id])
    new_row_ids = {}
    errors = []
    
    # If there are any errors, no changes should be saved
    ActiveRecord::Base.transaction do
      # Save Table-Level changes
      if !table.update_attributes(params[:rate_table])
        errors.concat(table.errors.to_a)
      end
      
      # Delete Removed Rows
      RateRow.transaction do
        params[:delete_rows] ||= {}
        params[:delete_rows].each do |row_id|
          RateRow.delete_all(:rate_row_id => row_id)
          RateCell.delete_all(:rate_row_id => row_id)
        end
      end
      
      # Update Existing Rows
      RateRow.transaction do
        params[:existing_rows] ||= {}
        params[:existing_rows].each do |row_id, values|
          row = RateRow.get(row_id)
          if row.save
            values.each do |rate_id, value|
              cell = row.get_cell(rate_id)
              if !cell.update_attributes(:value => value)
                errors.concat(cell.errors.to_a)
              end
            end
          else
            errors.concat(row.errors.to_a)
          end
        end
        if !errors.empty?
          # Don't throw an error until all validations are run to be sure
          # we have collected all the errror first
          raise ActiveRecord::Rollback, "Existing Rate Rows failed validation"
        end
      end
      
      # Create New Rows
      RateRow.transaction do
        params[:new_rows] ||= {}
        params[:new_rows].each do |row_num, values|
          new_row = RateRow.new(:audit_user => session[:user].user_name,
                      :effective_status => 'DRAFT',
                      :effective_date => DateTime.now)
          new_row.rate_table_id = table.rate_table_id
          if new_row.save
            new_row_ids[row_num] = new_row.rate_row_id
            # Create Rate Cells
            rates = Rate.for_template(table.template_id)
            rates.each do |rate|
              rate_cell = RateCell.new
              rate_cell.rate_row_id = new_row.rate_row_id
              rate_cell.rate_id = rate.rate_id
              rate_cell.rate_table_id = table.rate_table_id
              rate_cell.value = values[rate.rate_id]
              if !rate_cell.save
                errors.concat(rate_cell.errors.to_a)
              end
            end
          else
            errors.concat(new_row.errors.to_a)
          end
        end
        if !errors.empty?
          # Don't throw an error until all validations are run to be sure
          # we have collected all the errror first
          raise ActiveRecord::Rollback, "Rate Rows failed validation"
        end
      end
      
      # If there are errors at this point, go ahead and quit without 
      # checking for duplicate rows
      raise ActiveRecord::Rollback, "There were errors updating the rate table" if errors.any?
      
      # Make sure there are no duplicate rows
      rows = table.rate_rows
      normalized_rows = []
      rows.each do |row|
        cells = row.get_cells(table.template_id)
        normalized_row = ''
        cells.each do |cell|
          normalized_row += "#{cell.value},"
        end
        if normalized_rows.include?(normalized_row)
          # this is an expensive search, quit on first error
          errors << "One or more rows are duplicates, each row much be unique"
          raise ActiveRecord::Rollback, "Rate table has duplicate rows"
        else
          normalized_rows << normalized_row
        end
      end
    end
    
    if errors.empty?
      render json: {success: true, newIds: new_row_ids}, status: :ok
    else
      render json: errors, status: :unprocessable_entity
    end
  end
  
  def create
    @table = RateTable.new(params[:rate_table])
    @table.effective_date = DateTime.now
    @table.effective_status = 'DRAFT'
    @table.audit_user = session[:user].user_name
    if @table.save
      flash[:success] = "Rate Table successfully created"
      redirect_to @table
    else
      render :new
    end
  end
  
  def destroy
    RateTable.transaction do
      RateCell.delete_all(:rate_table_id=>params[:id])
      RateRow.delete_all(:rate_table_id=>params[:id])
      RateTable.delete_all(:rate_table_id=>params[:id])
      flash[:success] = "Rate table successfully deleted"
    end
    
    redirect_to :action => :index
  end
  
    private
      
      def setup_sessions
        session[:usage_template_name] = params[:template_name] || session[:usage_template_name]
        session[:usage_template_code] = params[:template_code] || session[:usage_template_code]
        session[:rate_table_name]     = params[:rate_table_name] || session[:rate_table_name]
        session[:rate_table_status]   = params[:rate_table_status] || session[:rate_table_status]
        session[:rate_table_order]    = params[:order] || session[:rate_table_order] || "title asc"
        session[:rate_table_amount]   = params[:amount] || session[:rate_table_amount] || "10"
      end
end

app/views/rate_tables/_errors.html.erb
<% if @table.errors.any? %>
  <ul class="text-error">
    <% @table.errors.each do |error, message| %>
      <li><%= RateTable.human_attribute_name(error) %> - <%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/rate_tables/_form.html.erb
<%= render "errors" %>

<%= form_for(@table, :html => {:class=>"form-horizontal"}) do |f| %>

  <div class="control-group">
    <%= f.label "Name", :class=> "control-label" %>
    <div class="controls">
      <%= f.text_field :title, :class=> "span3", :required=> true, :maxlength=> 50 %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label "Template", :class=> "control-label" %>
    <div class="controls">
      <%= f.collection_select(:template_id, @table.avaliable_templates, :template_id, :template_name,
                              {:selected => @table.template_id, :include_blank => true},
                               :class=> "span3 no-left-margin", :data => {:type => "select2" } ) %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to "Cancel", :back, :class=> "btn" %>
    <%= f.submit "Save", :class=> "btn btn-primary" %>
  </div>
<% end %>

app/views/rate_tables/_table.html.erb
<table id="rate-table" class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <% rates = @table.rates %>
      <% rows = @table.rate_rows %>
      <th><input type="checkbox" data-role="checkall" data-check-name="rows[]"></th>
      <% rates.each do |rate| %>
        <th>
          <%= rate.title %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% rows.each do |row| %>
      <% cells = row.get_cells(@table.template_id) %>
      <tr data-row="<%= row.rate_row_id %>">
        <td>
          <input type="checkbox" class="no-top-margin" name="rows[]">
          <i class="icon-copy hover" title="Copy row" data-role="copy-rate-row"></i>
          <i class="icon-trash hover" title="Delete row" data-role="delete-rate-row"></i>
        </td>
        <% rates.each do |rate| %>
        <td>
          <% if rate.group_code && !rate.group_code.empty? %>
            <a data-type="select"
               data-role="editable"
               tabindex="<%=autotab%>"
               title="Enter <%=rate.title%>"
               data-saved-value="<%= cells.select{|v| v.rate_id == rate.rate_id }.first.value%>"
               data-source="<%= general_code_item_path(rate.group_code) %>"
               data-name="existing_rows[<%=row.rate_row_id%>][<%=rate.rate_id%>]"
               data-value="<%= cells.select{|v| v.rate_id == rate.rate_id }.first.value%>">
               <%= cells.select{|v| v.rate_id == rate.rate_id }.first.group_code_description(rate.group_code) %>
            </a>
          <% else %>
            <a data-type="text"
               data-role="editable"
               title="Enter <%=rate.title%>"
               tabindex="<%=autotab%>"
               data-saved-value="<%= cells.select{|v| v.rate_id == rate.rate_id }.first.value%>"
               data-name="existing_rows[<%=row.rate_row_id%>][<%=rate.rate_id%>]">
               <%= cells.select{|v| v.rate_id == rate.rate_id }.first.value%>
            </a>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
    
    <!-- Copied Rows -->
    <% @new_rows.each_with_index do |row, index| %>
      <% cells = row.get_cells(@table.template_id) %>
      <tr data-row="new">
        <td>
          <input type="checkbox" class="no-top-margin" name="rows[]">
          <i class="icon-copy hover" title="Copy row" data-role="copy-rate-row"></i>
          <i class="icon-trash hover" title="Delete row" data-role="delete-rate-row"></i>
        </td>
        <% rates.each do |rate| %>
        <td>
          <% cell = cells.select{|v| v.rate_id == rate.rate_id }.first %>
          <% if rate.group_code && !rate.group_code.empty? %>
            <a class="editable-unsaved"
               data-type="select"
               data-role="editable"
               tabindex="<%=autotab%>"
               title="Enter <%=rate.title%>"
               data-saved-value="<%= cell.value unless cell.nil? %>"
               data-source="<%= general_code_item_path(rate.group_code) %>"
               data-name="new_rows[<%=index%>][<%=rate.rate_id%>]"
               data-value="<%= cell.value unless cell.nil? %>">
               <%= cell.group_code_description(rate.group_code)  unless cell.nil? %>
            </a>
          <% else %>
            <a class="editable-unsaved"
               data-type="text"
               data-role="editable"
               title="Enter <%=rate.title%>"
               tabindex="<%=autotab%>"
               data-saved-value="<%= cell.value unless cell.nil? %>"
               data-name="new_rows[<%=index%>][<%=rate.rate_id%>]">
               <%= cell.value unless cell.nil? %>
            </a>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
    
    
    <tr class="hidden">
      <td>
        <input type="checkbox" class="no-top-margin" name="rows[]">
        <i class="icon-copy hover" title="Copy row" data-role="copy-rate-row"></i>
        <i class="icon-trash hover" title="Delete row" data-role="delete-rate-row"></i>
      </td>
      <% rates.each do |rate| %>
        <td>
          <% if rate.group_code && !rate.group_code.empty? %>
            <a data-type="select"
               class="editable-unsaved"
               title="Enter <%=rate.title%>"
               data-role="editable"
               data-saved-value=""
               data-source="<%= general_code_item_path(rate.group_code) %>"
               data-name="[<%=rate.rate_id%>]">
            </a>
          <% else %>
            <a data-type="text"
               class="editable-unsaved"
               title="Enter <%=rate.title%>"
               data-role="editable"
               data-saved-value=""
               data-name="[<%=rate.rate_id%>]">
            </a>
          <% end %>
        </td>
      <% end %>
    </tr>
  </tbody>
</table>

<div id="edit-rate-rows" class="modal hide fade modal-wide">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Edit selected rate rows</h3>
  </div>
  <div class="modal-body">
    <table class="table table-striped table-hover table-condensed">
      <thead>
        <tr>
          <% rates.each do |rate| %>
            <th>
              <%= rate.title %>
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% rates.each_with_index do |rate, index| %>
            <% position = 'right' %>
            <% position = 'left' if index == rates.length-1 %>
            <td>
              <% if rate.group_code && !rate.group_code.empty? %>
                <a data-type="select"
                   title="Enter <%=rate.title%>"
                   data-role="editable"
                   data-placement="<%= position %>"
                   data-source="<%= general_code_item_path(rate.group_code) %>"
                   data-name="[<%=rate.rate_id%>]">
                </a>
              <% else %>
                <a data-type="text"
                   title="Enter <%=rate.title%>"
                   data-role="editable"
                   data-placement="<%= position %>"
                   data-name="[<%=rate.rate_id%>]">
                </a>
              <% end %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <a id="save-selected-changes" class="btn btn-primary">Save changes</a>
  </div>
</div>

app/views/rate_tables/_toolbar.html.erb
<div style="height:50px;">
  <div class="container toolbar affix-top" data-spy="affix" data-offset-top="307">
    <div class="btn-toolbar touching_toolbars span11 no-left-margin">
      <div class="btn-group">
        <button class="btn" data-role="add-row">
          <i class="icon-th-list"></i> Add Row
        </button>
        <button class="btn" data-role="edit-selected-rates">
          <i class="icon-pencil"></i> Edit Selected
        </button>
        <button class="btn" data-role="delete-selected-rates">
          <i class="icon-trash"></i> Delete Selected
        </button>
        <%= link_to(rate_table_path(@table), :method => :delete, :confirm => "Are you sure you want to delete this rate table and all its rows?", :class => "btn") do %>
          <i class="icon-trash"></i> Delete Rate Table
        <% end %>
        <%= link_to rate_table_rate_rows_path(@table), :class => "btn" do %>
          <i class="icon-copy"></i> Find Rate Rows
        <% end %>
        <button class="btn" data-role="reset-rate-table" title="Reset table to last saved state (Ctrl+Z)">
          <i class="icon-undo"></i> Reset
        </button>
        <button class="btn btn-success"
                id="save-rate-table"
                data-url="<%= rate_table_update_path(@table)%>"
                title="Save all changes to the rate table (Ctrl+S)">
          <i class="icon-hdd"></i> Save
        </button>
      </div>
    </div>
    <div class="btn-toolbar span">
      <div id="rates-loading" class="loading hide"></div>
    </div>
 </div>
</div>

app/views/rate_tables/index.html.erb
<% content_for(:page_title) do "Rate Tables" end %>

<h2>Search Rate Tables</h2>

<div class="well">
  <a href="<%=new_rate_table_path%>">
    <i class="icon-plus hover pull-right" title="Create a new rate table"></i>
  </a>
  <form class="span8 form-horizontal search" method="get">
    <input type="text"
      class="input-large"
      placeholder="Table Name"
      name="rate_table_name"
      value="<%=session[:rate_table_name]%>" >
    <input type="text"
      class="input-large"
      placeholder="Template Name"
      name="template_name"
      value="<%=session[:usage_template_name]%>" >
    <input type="text"
      class="input-large"
      placeholder="Table Status"
      name="rate_table_status"
      value="<%=session[:rate_table_status]%>" >
    <input type="text"
      class="input-large"
      placeholder="Template Code"
      name="template_code"
      value="<%=session[:usage_template_code]%>" >
    <div class="btn-group">
      <button class="btn" type="button" data-role="clear-form"><i class="icon-remove"></i></button>
      <button type="submit" class="btn"><i class="icon-search"></i></button>
    </div>
  </form>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th><%=sortable @tables, "Table Name", "title" %></th>
        <th><%=sortable @tables, "Template Code", "template_code" %></th>
        <th><%=sortable @tables, "Template Name", "template_name" %></th>
        <th><%=sortable @tables, "Status", "rate_tables.effective_status" %></th>
      </tr>
    </thead>
      <% @tables.each do |table| %>
        <tr>
          <td><%= link_to table.title, rate_table_path(table.rate_table_id) %></td>
          <td><%= link_to table.template_code, template_path(table.template_id) %></td>
          <td><%= link_to table.template_name, template_path(table.template_id) %></td>
          <td><%= table.effective_status %></td>
        </tr>
      <% end %>
  </table>
  
  <div class="container">
    <div class="table-footer span3">
      <%= form_tag({:controller=>:rate_tables, :action=>:index}, :method=>:get) do %>
        <%= select_tag( "amount",
                        options_from_collection_for_select(pagination_options, :last, :first, session[:rate_tables_amount]),
                        :class => "input-mini",
                        data: {role: "pagination-amount"} )%>
      <% end %>
    </div>
    <%= paginate @tables %>
  </div>
</div>

app/views/rate_tables/new.html.erb
<% content_for(:page_title) do "Create Rate Table" end %>

<h2>Create Rate Table</h2>
<div class="well">
  <%= render "form" %>
</div>

app/views/rate_tables/show.html.erb
<% content_for(:page_title) do @table.title + " | Rate Table" end %>

<h2>Edit Rate Table</h2>

<div class="well">
  <table class="table table-condensed no-bottom-margin borderless">
    <tr>
      <th>Name</th>
      <th>Template Code</th>
      <th>Template Name</th>
      <th>Date</th>
      <th>Status</th>
    </tr>
    <tr>
      <td>
        <a data-role="editable"
           data-type="text"
           data-name="rate_table[title]"
           data-placement="right"
           tabindex="<%=autotab%>"
           data-saved-value="<%= @table.title %>"
           title="Enter Rate Table name">
           <%= @table.title %>
        </a></td>
      <td><%= @table.template.template_code %></td>
      <td><%= @table.template.template_name %></td>
      <td>
        <a data-role="editable"
           data-type="date"
           data-name="rate_table[effective_date]"
           data-clear="false"
           data-placement="right"
           data-saved-value="<%= @table.effective_date.to_date.strftime("%F") %>"
           data-viewformat="mm-dd-yyyy"
           data-format="yyyy-mm-dd"
           tabindex="<%=autotab%>"
           title="Enter Effective Date">
           <%= @table.effective_date.to_date %>
        </a></td>
      <td><%= @table.effective_status %></td>
    </tr>
  </table>
</div>

<%= render "toolbar" %>

<div class="well">
  <%= render "table" %>
</div>