config/routes.rb
PpPricing::Application.routes.draw do

  root :to => "products#index"

  resource :sessions, :only=> [:new, :create] do
    collection do
      get 'logout'
    end
  end

  resources :rate_results
  resources :rate_determinants
  resources :price_plans, :constraints => { :id => /.*/ }
  resources :services, :only => [:index, :edit]
  resources :zonal_coverages
  resources :tariff_tier_tapers, :constraints => { :id => /.*/ }
  resources :tariff_zones, :constraints => { :id => /.*/ }
  resources :general_code_items, :only => [:show]
  resources :pricing_structures, :only => [:edit]
  resources :service_characteristics, :only => [:index, :edit]
  resources :promotions, :only => [:index, :edit]
  resources :event_creation_templates, :only => [:index, :edit], :constraints => { :id => /.*/ }

  resources :templates do
    get :select_rate_determinants
    get :select_rate_results
    post :update_with_rates
    post :approve
    resources :rates
  end

  resources :tariff_model_areas, :constraints => { :id => /.*/ } do
    get :approve
    get :revert
    collection do
      post :calculation_options
      post :tmes
    end
  end

  resources :products, :only => [:index, :edit] do
    collection do
      get :synchronize
    end
  end

  resources :rate_tables, :except=> [:update] do
    post :update # changing the default `put update` to a post for use with x-editable
    resources :rate_rows, :only => [:index]
    post :show
  end

  resource :tools, :only=> [:index] do
     collection do
       get 'upload'
     end 
  end 

end

app/models/selection_rule_condition.rb
class SelectionRuleCondition < ActiveRecord::Base
  require 'securerandom'
  require 'ostruct'
  self.table_name = :selection_rule_condition
  self.primary_key = :condition_id

  before_create :default_values
  attr_accessible :condition_name, :condition_text, :description
  #belongs_to :algorithm_selection_rule

  validates :condition_name, :presence => true, :length => { :maximum => 16 }
  validates :condition_text, :presence => true, :length => { :maximum => 512 }
  validates :description, :presence => true, :length => { :maximum => 60 }
  
  @event_details

  def self.for_condition_id(condition_id)
    find(condition_id)
  end
  
  def self.event_details(condition_id, condition_string)
    events = condition_string.scan(/\([^)]*\)|\S+\s+(?:==|!=|<>|<|>|<=|>=|is)\s+\S+/)
    self.parse_events(events, condition_id)
  end
  
protected
    # Called before create (insert), only sets the default value
    # if it has not already been set. 
    def default_values
      # Create a unique ID
      unique = Time.now.to_f.to_s.gsub('.','').to_i.to_s(36)
      unique += Random.rand("9".ljust(16-unique.length,"9").to_i).to_s
      self.condition_id ||= unique
      
      # Handle other defaults
      self.update_number ||= 1
      self.audit_update_date_time ||= DateTime.now
      self.effective_status ||= 'ACTIVE'
      self.effective_date ||= DateTime.now
    end
    
    def self.parse_events(events, condition_id)
      event_details = []
      order_string = ""
      original_operator = select("cce.comparison_operator_value_rd")
                              .from("char_condition_expression cce")
                              .where("cce.sr_condition_id = :condition_id", {:condition_id => condition_id})
      if original_operator.size > 0
        original_operator = original_operator.first.comparison_operator_value_rd
      else
        original_operator = ""
      end
      events.each_with_index do |event, i|
        event_detail = OpenStruct.new
        event_detail.order = (i + 97).chr # set order
        logic_operator = select("co.operator_value_rd") # grab "and"/"or"
                             .from("condition_operator co")
                             .where("co.sr_condition_id = :condition_id", {:condition_id => condition_id}).first
        logic_operator = logic_operator.operator_value_rd unless logic_operator.nil?
        pieces = event.scan(/[\S]+/) # split event into pieces
        pieces[0] = pieces[0].gsub(/^\(/, '') # remove leading parentheses
        condition_expression = select("*") # table which is accessed for several attributes
                                   .from("priceable_characteristic pc")
                                   .where("pc.rtti_path = :path", {:path => pieces[0]}).first
        if !condition_expression.nil?
          event_detail.type = condition_expression.characteristic_type_value_rd # set type
          event_detail.name = condition_expression.name # set name
        else
          event_detail.type = '(unknown)'
          event_detail.name = pieces[0] # the proper name couldn't be found so use the rtti_path
        end
        operator = pieces[1]
        event_detail.operator = operator # set operator
        value_string = ""
        group_code = condition_expression.value_group_rd unless condition_expression.nil?
        
        # build order string
        if(i != 0)
          order_string += logic_operator unless logic_operator.nil?
          order_string += " "
        end
        order_string += event_detail.order + " "
        
        # build value string
        pieces.each_with_index do |item, j|
          position = j % 4
          if(position == 2) # parse value
            value = item
            value = value.gsub(/["\)]/, '')
            value = self.parse_value(value, group_code)
            value_string += value + ' '
          elsif(position == 3) # parse and/or
            if(operator != original_operator && item == "and")
              item = "or"
            elsif(operator != original_operator && item == "or")
              item = "and"
            end
            value_string += item + ' '
          end
        end
        event_detail.values = value_string # set value
        event_details << event_detail # add populated row
      end
      if event_details.size == 0 # If there were no events
        event_details << OpenStruct.new
      end
      event_details[0].order_string = order_string # set order string
      return event_details
    end
    
    def self.parse_value(value, group_code)
      group_item = GeneralCodeItem.where(:group_code => group_code, :value => value).first
      if group_item.nil?
        return value
      else
        value = group_item.description
        return value
      end
    end

end

app/views/selection_rule_conditions/_condition.html.erb
<% if @condition.errors.any? %>
  <ul class="text-error">
    <% @condition.errors.each do |error, message| %>
      <li><%= PricePlan.human_attribute_name(error) %> - <%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@rule, @condition, :html => {:class=>"form-horizontal"}) do |f| %>

  <div class="form-actions">
    <%= link_to "Cancel", :back, :class=> "btn" %>
    <%= f.submit "Save", :class=> "btn btn-success" %>
  </div>

  <div class="control-group">
    <%= f.label "Condition code", :class=> "control-label" %>
    <div class="controls">
      <%= f.text_field :condition_code, :required=> true, :class=> "span2", :maxlength=> 16 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Condition Name", :class=> "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :required=> true, :class=> "span2", :maxlength=> 16 %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label "Description", :class=> "control-label" %>
    <div class="controls">
      <%= f.text_field :descriptive_text, :required=> true, :class=> "span4", :maxlength=> 60 %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label "Condition Text", :class=> "control-label" %>
    <div class="controls">
      <%= f.text_field :condition_string, :required=> true, :maxlength=> 512 %>
    </div>

  </div>

<% end %>

app/views/selection_rule_conditions/_rules.html.erb
  <%if @rule.target_type = "C" %>
  <div class="control-group">
    <div class="control-label" >Condition</div>
     <div class="controls">
      <a href="<%= price_plan_algorithm_selection_rule_selection_rule_condition_path(@price_plan.price_plan_version_id, @rule.selection_rule_id, @rule.condition_id) %>"><%=@rule.name%></a>
     </div>
    </div>
  </div>
  <% else %>
  <div class="control-group">
    <div class="control-label" >Algorithm</div>
    <div class="controls">
      <a href="<%= price_plan_algorithm_selection_rule_algorithm_path(@price_plan.price_plan_version_id, @rule.selection_rule_id, @rule.algorithm_id) %>"><%=@rule.name%></a>
    </div>
  </div>
  </div>
  <%end%>

  <div class="control-group">
     <div class="control-label" >True Rule</div>
     <% unless @rule.true_rule_id.nil? %>
    <div class="controls">
       <%true_rule=AlgorithmSelectionRule.get_rule_info(@rule.true_rule_id)%>
      <a href="<%= price_plan_algorithm_selection_rule_path(@price_plan.price_plan_version_id, @rule.true_rule_id) %>"><%true_rule.name%></a>
    </div>
    <%end%>
  </div>

  <div class="control-group">
     <div class="control-label" >False Rule</div>
     <% unless @rule.false_rule_id.nil? %>
    <div class="controls">
       <%false_rule=AlgorithmSelectionRule.get_rule_info(@rule.false_rule_id)%>
      <a href="<%= price_plan_algorithm_selection_rule_path(@price_plan.price_plan_version_id, @rule.false_rule_id) %>"><%=false_rule.name%></a>
    </div>
    <%end%>
  </div>

app/views/selection_rule_conditions/edit.html.erb
<h2>Edit Price Plan</h2>
<div class="well">
  <%= render "form" %>
</div>

app/views/selection_rule_conditions/index.html.erb
<h2>Search Price Plan</h2>

<div class="well">

  <form class="span5 form-horizontal" method="get">
    <input type="text"
      class="input-large"
      placeholder="Price Plan Code"
      name="price_plan_code"
      value="<%=session[:price_plan_code]%>" >
    <input type="text"
      class="input-large"
      placeholder="Name"
      name="name"
      value="<%=session[:name]%>" >
    <div class="btn-group">
      <button class="btn" type="button" data-role="clear-form"><i class="icon-remove"></i></button>
      <button type="submit" class="btn"><i class="icon-search"></i></button>
    </div>
  </form>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th/>
        <th><%=sortable @price_plans, "Code", "price_plan_code" %></th>
        <th><%=sortable @price_plans, "Name", "name" %></th>
      </tr>
    </thead>
    <tbody>
      <% @price_plans.each do |pp| %>
        <tr>
	  <td>
            <%= link_to price_plan_path(pp.price_plan_version_id),
              method: :delete, data: { confirm: "Are you sure you want to delete this price plan?" } do %>
              <i class="icon-trash hover"> </i>
            <% end %>
	  </td>
          <td><%= link_to pp.price_plan_code, edit_price_plan_path(:id => pp.price_plan_version_id) %></td>
          <td><%= link_to pp.descriptive_text, edit_price_plan_path(:id => pp.price_plan_version_id)  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="container">
    <div class="table-footer span3">
      <%= form_tag({:controller=>:price_plans, :action=>:index}, :method=>:get) do %>
        <%= select_tag( "amount",
                        options_from_collection_for_select(pagination_options, :last, :first, session[:feedback_amount]),
                        :class => "input-mini",
                        data: {role: "pagination-amount"} )%>
      <% end %>
    </div>
    <%= paginate @price_plans %>
  </div>
</div>

app/views/selection_rule_conditions/new.html.erb
<h2>Create Price Plan</h2>
<div class="well">
  <%= render "form" %>
</div>

app/views/selection_rule_conditions/show.html.erb
<h2>Edit Price Plan</h2>
<div class="well">
  <%= render "form" %>
</div>